### ISSUE TITLE
Not possible manage protocol connection WS/WSS

### ISSUE THREAD

**Issue by md2k** [graarh/golang-socketio#1]
There is no way to manage protocol between normal and secure.
My proposal it will be better pass thru URL to your internal Dial() and inside check if url passed correctly.
for example i can build URL this way:
```go
go run main.go -url wss://example.com:9998/socket.io/ -token 71553793b0a0c8dad3950c7f12b3b7c7

main.go:
	flag.StringVar(&Url, "url", "ws://127.0.0.1:9999/socket.io/", "websocket URL")
	flag.StringVar(&Token, "token", "", "Token for WS Authentication")

        _url, _ := url.Parse(Url)
	fmt.Println(_url.Scheme, _url.Host, _url.Path)
	u := url.URL{Scheme: _url.Scheme, Host: _url.Host, Path: _url.Path, RawQuery: fmt.Sprintf("transport=websocket&token=%s", Token)}
        c, err := gosocketio.Dial(u.String(), transport.GetDefaultWebsocketTransport())
	if err != nil {
		log.Fatal("Dial Error:", err)
	}

.... rest
```

This will allow instantly manage what type of connection will be established Non-SSL or SSL
URL will be properly assembled, then its parts can be used to check if everything passed properly and assembled back again with URL lib.

or if you not like pas full URL, you can pass only host:port and then use structure as options set which will be used to assemble proper URL with protocol, Path and query params.
Using [String addition by "+"](https://github.com/graarh/golang-socketio/blob/52ee6ec03c1c02e7e71a9f22ed80fea4737b4015/transport/websocket.go#L97) most probably not best idea.

I can write patch if you want (only let me know which way you prefer 1st or 2nd from above and do not broke you main functionality as you most probably use this work some where for yourself), since i going to use your library for performance tests for my WS backends.

**Comment by graarh** [comment]
I changed it both ways. Now you can pass the url to Dial method. But if you need an url generator you can use gosocketio.GetUrl(host string, port int, secure bool) method.

**Comment by md2k** [comment]
Thanks for change, but you still didnt count that you maybe want pass additional URL parameters (query strings with initial request)
For example server side may use token authorization and if token invalid connection will be closed.
So maybe then it better to add to GetUrl additional parameter:
```
func GetUrl(host string, port int, params []string, secure bool) string {
	var prefix string
	if secure {
		prefix = webSocketSecureProtocol
	} else {
		prefix = webSocketProtocol
	}

	_url, err := url.Parse(prefix + host + ":" + strconv.Itoa(port) + socketioUrl)
	if err != nil {
		fmt.Println("We unable to parse given url: ", _url)
	}

	if len(params) > 0 {
		_uval := _url.Query()
		fmt.Println("Qury: ", _uval)
		for _, element := range params {
			s := strings.Split(element, "=")
			_uval.Add(s[0], s[1])
		}
		_url.RawQuery = _uval.Encode()
	}

	return _url.String()
}
```

Then we can do next thing:
```
	var params []string
	params = append(params, fmt.Sprintf("token=%s", Token))
	params = append(params, "something=blabla")
        _url := gosocketio.GetUrl(Host, Port, params, true)
	c, err := gosocketio.Dial(_url, transport.GetDefaultWebsocketTransport())
	if err != nil {
		log.Fatal("Dial Error:", err)
	}

As result we will get final URL as:
Query Before Add params:  map[EIO:[3] transport:[websocket]]
URL Before Add params:  wss://localhost:9998/socket.io/?EIO=3&transport=websocket
Query After Add params:  map[EIO:[3] transport:[websocket] token:[71553793b0a0c8dad3950c7f12b3b7c7] something:[also]]
Fina URL:  wss://localhost:9998/socket.io/?EIO=3&something=also&token=71553793b0a0c8dad3950c7f12b3b7c7&transport=websocket
```

**Comment by md2k** [comment]
@graarh can you take a look here ?
