### ISSUE TITLE
Concurrency support.

### ISSUE THREAD

**Issue by happierall** [graarh/golang-socketio#14]
Your code can't work with concurrency. Read [gorilla docs](https://godoc.org/github.com/gorilla/websocket#hdr-Concurrency).

https://github.com/graarh/golang-socketio/blob/master/transport/websocket.go#L60 it is not concurrency safe.

**Comment by graarh** [comment]
Try it byself, it worked with multiple concurrent connections well. 

Yes, gorilla websocket connection is not thread-safe. But look at loop.go file, inLoop and outLoop functions. They use only one read and only one write thread for every connection. 

You can look at http://peka2.tv site, for example. Chat server uses this library, and handles thousands of users well.

**Comment by happierall** [comment]
You can't write in one channel by two goroutine.

**Comment by graarh** [comment]
You can, look the outLoop code. It takes your several goroutines calls one by one from channel. 

This is the part that starts code, that is not thread safe
```go
                err := c.conn.WriteMessage(msg)
		if err != nil {
			return CloseChannel(c, m, err)
		}
```
and you can grep that this is single place to call WriteMessage function.

**Comment by graarh** [comment]
It may be tricky to overlook the whole logic, ill try to describe it.

For example, look the send.go:45, Emit function. It used for sending common messages over websocket. It uses send function (send.go:18)

Send does not sends data directly to websocket, it places them into output query (send.go:37)
```go
	c.out <- command
```

So, if you want to use Emit function in multiple goroutines, it will collect your messages in output queue channel.

Now take a look at the outLoop function (loop.go:152) It processes messages from this queue one by one. It starts only once for every connection.
```go
		msg := <-c.out
		if msg == protocol.CloseMessage {
			return nil
		}

		err := c.conn.WriteMessage(msg)
		if err != nil {
			return CloseChannel(c, m, err)
		}
```

And never uses more than one goroutine to call WriteMessage. So the final socket.io gorilla method used correctly.
