### ISSUE TITLE
close a channel from the server side

### ISSUE THREAD

**Issue by oldshuren** [graarh/golang-socketio#16]
Hi,

I could not find the function to close a channel from the server side. There is a public function CloseChannel(), but it takes *methods as argument. Where can I get *methods? The methods on the Server is private.

Thanks!

**Comment by graarh** [comment]
Hi!

You can use c.server.methods, e.g.

```go
func HandleConnect(ch *gosocketio.Channel, args interface{}) {
    gosocketio.CloseChannel(ch, ch.server.methods, nil)
}
```

But this looks like a hack (

I will add ch.Close() function

**Comment by oldshuren** [comment]
Hi graarh,

Just as I said in my first message. ch.erver.method is not exported. In order to export a field, you need to name it with a capital letter, like Server and Methods. 

Here was go printed out,

bash-3.2$ go run s.go
# command-line-arguments
./s.go:43: ch.server undefined (cannot refer to unexported field or method server)

**Comment by oldshuren** [comment]
By the way, I added a function 
func (c *Channel) Close() error {
	return CloseChannel(c, &(c.server.methods), nil)
}
But if I send something right before close, the message is not flushed to the client side. That is, if I do
c.Emit("Unauthorized")
c.Close()
The event "Unauthorized" never reach client.

Thanks!

**Comment by graarh** [comment]
Yes, this is correct behaviour. Emit adds package to output queue (without waiting for sending through socket), but CloseChannel closes connection instantly.

If you want to send and close after, you can send ack request, and close then you receive the result.

**Comment by oldshuren** [comment]
Thanks!

But I don't want to make my code too complicated. So I just sleep for 1 millisecond before close()
